name: test
on: push
jobs:
  build:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: xcframework
      run: python3 build_framework.py build
    - uses: actions/upload-artifact@v3
      with:
        name: xatlas.xcframework
        path: build/xatlas.xcframework